project:
  type: website
  output-dir: docs

website:
  title: "Learning Survey Solutions"
  search: true
  navbar:
    logo: suso_logo.png
    pinned: true
    background: "#3346d3"
    right:
      - text: "Home"
        icon: "house-door-fill"
        file: index.qmd
      - text: "Schedule"
        icon: "calendar-week"
        file: schedule.qmd
      - text: "Course"
        icon: "mortarboard"
        href: course/00_overview.qmd
      - text: "Assignments"
        icon: "journal-code"
        file: assignments/00_overview.qmd
      - text: "Resources"
        icon: "book"
        href: resources.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
