---
format: 
    revealjs: 
        theme: [default, ../../css/core.scss, ../../css/colors.scss]
        height: 900
        width: 1600
highlight-style: github
execute: 
  eval: false
  echo: true
---

```{r}

```

# Designer: the whole game {background-color=var(--suso)}


## Roadmap `r fontawesome::fa(name = "route")` {.suso}

::: {.box .box-s}
Login `r fontawesome::fa(name = "right-to-bracket")`
:::

::: {.box .box-s}
Search `r fontawesome::fa(name = "magnifying-glass")`
:::

::: {.box .box-s}
Create `r fontawesome::fa(name = "folder-plus")`
:::

::: {.box .box-s}
Develop `r fontawesome::fa(name = "laptop-code")`
:::

::: {.box .box-s}
Test `r fontawesome::fa(name = "vial-circle-check")`
:::

::: {.box .box-s}
Share `r fontawesome::fa(name = "share-from-square")`
:::


## Login `r fontawesome::fa(name = "right-to-bracket")` {.suso}

TODO: video of:

- navigate to URL
- provide login and password

## Search `r fontawesome::fa(name = "magnifying-glass")` {.suso}

TODO: video of: 

- click on `QUESTIONNAIRES SHARED WITH ME`, `PUBLIC`, `MY QUESTIONNAIRES` tabs
- use search bar 

## Create `r fontawesome::fa(name = "folder-plus")` {.suso}

TODO: video of:

- Click button to create
- Provide name and variable name
- Show name and variable name in UI

## Develop `r fontawesome::fa(name = "laptop-code")` {.suso}

TODO: video of:

- Add sections
- Add questions (creating a duplicate question to trigger compile error on purpose)
- Add roster
- Add (enablement) conditions

## Test `r fontawesome::fa(name = "vial-circle-check")` {.suso}

- TODO: video of:

- press COMPILE
- see error, hover over, click on link, remedy; press COMPILE again
- press TEST

## Share `r fontawesome::fa(name = "share-from-square")` {.suso}

TODO: video of:

- Click share button
- Provide email/user name
- Toggle permissions
- Send edit request