---
format: 
    revealjs: 
        theme: [default, ../../css/core.scss, ../../css/colors.scss]
        height: 900
        width: 1600
execute: 
  echo: false
  warning: false
  error: false 
---

# Question types {background-color=var(--suso)}

## Roadmap `r fontawesome::fa(name = "route")` {.suso}

:::: {.columns}

<!-- First column -->

::: {.column width="33%"}


::: {.box .box-1}
Overview `r fontawesome::fa(name = "tower-observation")`
:::

:::

<!-- Second column -->

::: {.column width="33%"}

::: {.box .box-2}
Categorical `r fontawesome::fa(name = "check")` / `r fontawesome::fa(name = "check-double")`
:::

::: {.box .box-3}
Numeric `r fontawesome::fa(name = "1")``r fontawesome::fa(name = "2")``r fontawesome::fa(name = "3")`
:::

::: {.box .box-4}
Text `r fontawesome::fa(name = "comment")` / `r fontawesome::fa(name = "bars")`
:::

::: {.box .box-5}
Date `r fontawesome::fa(name = "calendar")` / `r fontawesome::fa(name = "stopwatch")` 
:::

:::


<!-- Third column -->

::: {.column width="33%"}

::: {.box .box-6}
Sensors `r fontawesome::fa(name = "location-dot")` / `r fontawesome::fa(name = "camera")` / `r fontawesome::fa(name = "barcode")` / `r fontawesome::fa(name = "microphone")`
:::

::: {.box .box-7}
Geography `r fontawesome::fa(name = "draw-polygon")`
:::

:::

::::

# Overview `r fontawesome::fa(name = "tower-observation")` {background-color=var(--s1)}

{{< include _overview.qmd >}}

# Categorical `r fontawesome::fa(name = "check")` / `r fontawesome::fa(name = "check-double")` {background-color=var(--s2)}

{{< include _categorical.qmd >}}

# Numeric `r fontawesome::fa(name = "1")``r fontawesome::fa(name = "2")``r fontawesome::fa(name = "3")` {background-color=var(--s3)}

{{< include _numeric.qmd >}}

# Text `r fontawesome::fa(name = "comment")` / `r fontawesome::fa(name = "bars")` {background-color=var(--s4)}

{{< include _text.qmd >}}

# Date `r fontawesome::fa(name = "calendar")` / `r fontawesome::fa(name = "stopwatch")` {background-color=var(--s5)}

{{< include _date.qmd >}}

# Sensors `r fontawesome::fa(name = "location-dot")` / `r fontawesome::fa(name = "camera")` / `r fontawesome::fa(name = "barcode")` / `r fontawesome::fa(name = "microphone")` {background-color=var(--s6)}

{{< include _sensors.qmd >}}

# Geography `r fontawesome::fa(name = "draw-polygon")` {background-color=var(--s7)}
